version: 1.0.{build}

# 実行環境の指定
image: Visual Studio 2022

# 環境変数の設定 (AppVeyorの「Encrypt data」で作成した値をここに貼る)
environment:
  RDP_PASSWORD:
    secure: [qxqk7YETgxDEOgXZ/XmF/ACQctBMb7JTu3gCfCiQdh4=]
  CRD_AUTH_CODE:
    secure: [あなたの暗号化AuthCode]
  CRD_PIN:
    secure: [JvQ5xpCgQsyYdE7JYqAcWQ==]
  RDP_USERNAME: rdpadmin

# ビルド（セットアップ）工程
install:
  - ps: |
      Write-Host "Creating new local user..."
      $password = ConvertTo-SecureString $env:RDP_PASSWORD -AsPlainText -Force
      if (Get-LocalUser -Name $env:RDP_USERNAME -ErrorAction SilentlyContinue) {
        Remove-LocalUser -Name $env:RDP_USERNAME
      }
      New-LocalUser -Name $env:RDP_USERNAME -Password $password -FullName "RDP Admin User"
      Add-LocalGroupMember -Group "Administrators" -Member $env:RDP_USERNAME
      Add-LocalGroupMember -Group "Remote Desktop Users" -Member $env:RDP_USERNAME

  - ps: |
      $msiUrl = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
      $msiPath = Join-Path $env:TEMP "chrome-remote-desktop.msi"
      Write-Host "Installing Chrome Remote Desktop..."
      Invoke-WebRequest -Uri $msiUrl -OutFile $msiPath
      Start-Process msiexec.exe -Wait -ArgumentList "/i", "`"$msiPath`"", "/qn", "/norestart"
      Start-Sleep -Seconds 5

# メインの実行工程
build_script:
  - ps: |
      $crdPath = "${env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
      
      # INFOログをエラーと誤認させないための設定変更
      $oldPreference = $ErrorActionPreference
      $ErrorActionPreference = 'Continue'
      
      Write-Host "Starting Chrome Remote Desktop Host..."
      & $crdPath --code="$env:CRD_AUTH_CODE" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$env:COMPUTERNAME --pin="$env:CRD_PIN"
      
      $ErrorActionPreference = $oldPreference

      Write-Host "------------------------------------------"
      Write-Host "Chrome Remote Desktop 起動試行完了"
      Write-Host "設定したPINコード: $env:CRD_PIN"
      Write-Host "------------------------------------------"

      # AppVeyor無料枠の限界（60分）まで待機
      Start-Sleep -Seconds 3500
